---
    extends:
        - eslint:recommended
    parserOptions:
        ecmaVersion: 6
    env:
        node: true
        es6: true
    rules:
        no-undef: error
        no-console: off
        no-unused-vars: warn
        semi: error
        no-extra-semi: error
        no-extra-parens: error
        valid-jsdoc:
            - warn
            - requireReturn: false
        curly: error
        indent:
            - error
            - 4
            - SwitchCase: 1
        no-cond-assign:
            - error
            - always
        no-case-declarations: warn
        max-len: warn
    globals:
        _: false
        OK: false
        ERR_NOT_IN_RANGE: false
        ERR_NOT_ENOUGH_RESOURCES: false
        FIND_MY_CREEPS: false
        FIND_HOSTILE_CREEPS: false
        FIND_SOURCES: false
        FIND_DROPPED_ENERGY: false
        FIND_STRUCTURES: false
        FIND_MY_STRUCTURES: false
        FIND_FLAGS: false
        FIND_MY_CONSTRUCTION_SITES: false
        LOOK_TERRAIN: false
        MOVE: false
        WORK: false
        CARRY: false
        ATTACK: false
        RANGED_ATTACK: false
        TOUGH: false
        HEAL: false
        CLAIM: false
        BODYPART_COST: false
        HARVEST_POWER: false
        STRUCTURE_SPAWN: false
        STRUCTURE_EXTENSION: false
        STRUCTURE_ROAD: false
        STRUCTURE_WALL: false
        STRUCTURE_RAMPART: false
        STRUCTURE_KEEPER_LAIR: false
        STRUCTURE_LINK: false
        STRUCTURE_STORAGE: false
        STRUCTURE_TOWER: false
        STRUCTURE_CONTAINER: false
        STORAGE_CAPACITY: false
        MODE_SIMULATION: false
        CONTAINER_CAPACITY: false
        RESOURCE_ENERGY: false
        Game: false
        Memory: false
        PathFinder: false
        Room: false
        RoomPosition: false
        RoomObject: false
        Creep: false
        Resource: false
        Source: false
        Structure: false
        StructureController: false
        StructureLink: false
        StructureSpawn: false
        StructureStorage: false
        StructureTower: false
        StructureContainer: false
